name:                aoc2022
version:             0.1.0.0
github:              "fkrunic/advent-of-code-2022"
license:             BSD3
author:              "Filip Krunic"
maintainer:          "fkrunic9@gmail.com"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Solutions to Advent of Code 2022

dependencies:
- arithmoi
- base >= 4.7 && < 5
- containers
- ghc
- megaparsec
- monad-loops
- random
- text
- transformers

default-extensions:
  GeneralizedNewtypeDeriving
  ImportQualifiedPost
  OverloadedStrings
  RankNTypes
  RecordWildCards
  ScopedTypeVariables
  TupleSections

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Werror=incomplete-patterns

library:
  source-dirs: src

executables:
  aoc2022-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2022

tests:
  aoc2022-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2022
